// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsFyhbFmY2s3wp4FqOc1C3bskJZ8KPm3U',
    appId: '1:486017608860:web:4555145b869ad44fc9d159',
    messagingSenderId: '486017608860',
    projectId: 'claudiskegelapp',
    authDomain: 'claudiskegelapp.firebaseapp.com',
    storageBucket: 'claudiskegelapp.firebasestorage.app',
    measurementId: 'G-88M2CERJ42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5YVtCn9Ivnj-tbE4B3Wa0_nW3cVoUzBE',
    appId: '1:486017608860:android:53727579ad944a35c9d159',
    messagingSenderId: '486017608860',
    projectId: 'claudiskegelapp',
    storageBucket: 'claudiskegelapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKI1W48jELWB5qNOGaTakn0nj4cD8Afwo',
    appId: '1:486017608860:ios:75c2d358fddd2a1dc9d159',
    messagingSenderId: '486017608860',
    projectId: 'claudiskegelapp',
    storageBucket: 'claudiskegelapp.firebasestorage.app',
    iosBundleId: 'com.example.claudiskegelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKI1W48jELWB5qNOGaTakn0nj4cD8Afwo',
    appId: '1:486017608860:ios:75c2d358fddd2a1dc9d159',
    messagingSenderId: '486017608860',
    projectId: 'claudiskegelapp',
    storageBucket: 'claudiskegelapp.firebasestorage.app',
    iosBundleId: 'com.example.claudiskegelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsFyhbFmY2s3wp4FqOc1C3bskJZ8KPm3U',
    appId: '1:486017608860:web:4de29cb1f64e3112c9d159',
    messagingSenderId: '486017608860',
    projectId: 'claudiskegelapp',
    authDomain: 'claudiskegelapp.firebaseapp.com',
    storageBucket: 'claudiskegelapp.firebasestorage.app',
    measurementId: 'G-GP5RXDG0NC',
  );
}
